# Generated by Django 3.2.3 on 2021-06-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0004_ordermodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='userid',
            new_name='Userid',
        ),
    ]
