# Generated by Django 3.2.3 on 2021-06-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0005_rename_userid_customermodel_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='Userid',
            new_name='userid',
        ),
    ]
